### ISSUE TITLE
Stress test of ProducerConsumer

### ISSUE THREAD

**Issue by fommil** [eigengo/scalad#53]
Write a stress test that can be left for days / weeks to try and uncover any concurrency issues that might result in deadlock. I seen a few of these on our build machine, but I'm not 100% it is ProducerConsumer because the build machine has been known to go into deadlock on other tasks (e.g. Jenkin builds).

**Comment by fommil** [comment]
I wrote java stress tests for the java port in my java-common project

**Comment by janm399** [comment]
Nice. I'm out for most of this week, but I'll take a look over the weekend.

**Comment by fommil** [comment]
FYI https://github.com/fommil/common-utils/blob/master/src/test/java/com/github/fommil/utils/ProducerConsumerTest.java

**Comment by fommil** [comment]
this has turned out to be a rather handy piece of code! Pull parsing works exceptionally well to keep memory usage down on a large variety of data sources. I wrote a (proprietary, but trivial) paging JdbcTemplate that uses this for millions of rows, buffered to 1,000.
