### ISSUE TITLE
Publish to public Maven repo

### ISSUE THREAD

**Issue by janm399** [eigengo/scalad#7]
Publish the artefacts to public Maven repository.

**Comment by fommil** [comment]
@cornelf

**Comment by fommil** [comment]
Workaround for this is to fork this repo and `sbt publish-local`

**Comment by fommil** [comment]
@janm399 @cornelf @anirvanc hi guys - it would be really useful for everybody (now that the Lessons Learnt are hitting the twittersphere) if there was a build of scalad on sonatype.

**Comment by janm399** [comment]
I'll get on to it today.

**Comment by janm399** [comment]
This now uses the new _eigengo_ package names and container; and includes the fixed SerialisationSpec, but otherwise, it is the plain vanilla Scalad release.

**Comment by janm399** [comment]
All set; use 

``` scala
"org.eigengo" % "scalad" %% "1.3.0-EG"
```

or, if you must use Maven, write

``` xml
<dependency>
  <groupId>org.eigengo</groupId>
  <artifactId>scalad_2.10</artifactId>
  <version>1.3.0-EG</version>
</dependency>
```

[Akka-Patterns/#36](https://github.com/janm399/akka-patterns/issues/36) now follows.
