### ISSUE TITLE
Library Dependency line in README.md incorrect

### ISSUE THREAD

**Issue by hsunami** [eigengo/scalad#75]
Spent hours trying to install scalad. 

This line in your README is incorrect:

"org.eigengo" % "scalad" %% "1.3.0-EG"

This works for me:

"org.eigengo"       %   "scalad_2.10"       % "1.3.0-SNAPSHOT"

**Comment by janm399** [comment]
You are right; it should actually be `"org.eigengo" %% "scalad" % "1.3.0-EG"`; notice the `%%` after `"org.eigengo"`, not the other way around.
